//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace Efika.Crm.Web.BMSCTipoCambio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TipoCambio_pttBinding", Namespace="/bmsc/Clientes/TipoCambioService")]
    public partial class TipoCambioService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TipoCambioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TipoCambioService() {
            this.Url = global::Efika.Crm.Web.Properties.Settings.Default.Efika_Crm_Web_BMSCTipoCambio_TipoCambioService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TipoCambioCompletedEventHandler TipoCambioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TipoCambio", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TipoCambio_Response", Namespace="/bmsc/clientes/")]
        public TipoCambio_Response TipoCambio([System.Xml.Serialization.XmlElementAttribute(Namespace="/bmsc/clientes/")] TipoCambio_Request TipoCambio_Request) {
            object[] results = this.Invoke("TipoCambio", new object[] {
                        TipoCambio_Request});
            return ((TipoCambio_Response)(results[0]));
        }
        
        /// <remarks/>
        public void TipoCambioAsync(TipoCambio_Request TipoCambio_Request) {
            this.TipoCambioAsync(TipoCambio_Request, null);
        }
        
        /// <remarks/>
        public void TipoCambioAsync(TipoCambio_Request TipoCambio_Request, object userState) {
            if ((this.TipoCambioOperationCompleted == null)) {
                this.TipoCambioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTipoCambioOperationCompleted);
            }
            this.InvokeAsync("TipoCambio", new object[] {
                        TipoCambio_Request}, this.TipoCambioOperationCompleted, userState);
        }
        
        private void OnTipoCambioOperationCompleted(object arg) {
            if ((this.TipoCambioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TipoCambioCompleted(this, new TipoCambioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="/bmsc/clientes/")]
    public partial class TipoCambio_Request {
        
        private string pUsuarioField;
        
        private string pContrasenaField;
        
        private string pDominioField;
        
        /// <remarks/>
        public string pUsuario {
            get {
                return this.pUsuarioField;
            }
            set {
                this.pUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string pContrasena {
            get {
                return this.pContrasenaField;
            }
            set {
                this.pContrasenaField = value;
            }
        }
        
        /// <remarks/>
        public string pDominio {
            get {
                return this.pDominioField;
            }
            set {
                this.pDominioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="/bmsc/clientes/")]
    public partial class TipoCambio_Response {
        
        private decimal pTCContableField;
        
        private decimal pTCCompraField;
        
        private decimal pTCVentaField;
        
        private string pResultadoField;
        
        private string pMensajeField;
        
        /// <remarks/>
        public decimal pTCContable {
            get {
                return this.pTCContableField;
            }
            set {
                this.pTCContableField = value;
            }
        }
        
        /// <remarks/>
        public decimal pTCCompra {
            get {
                return this.pTCCompraField;
            }
            set {
                this.pTCCompraField = value;
            }
        }
        
        /// <remarks/>
        public decimal pTCVenta {
            get {
                return this.pTCVentaField;
            }
            set {
                this.pTCVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string pResultado {
            get {
                return this.pResultadoField;
            }
            set {
                this.pResultadoField = value;
            }
        }
        
        /// <remarks/>
        public string pMensaje {
            get {
                return this.pMensajeField;
            }
            set {
                this.pMensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TipoCambioCompletedEventHandler(object sender, TipoCambioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TipoCambioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TipoCambioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoCambio_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoCambio_Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591