//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace Efika.Crm.Web.BMSCEvaluarScoreService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EvaluarScore_pttBinding", Namespace="/bmsc/crm/EvaluarScoreService")]
    public partial class EvaluarScoreService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EvaluarScoreOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EvaluarScoreService() {
            this.Url = global::Efika.Crm.Web.Properties.Settings.Default.Efika_Crm_Web_BMSCEvaluarScoreService_EvaluarScoreService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EvaluarScoreCompletedEventHandler EvaluarScoreCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("EvaluarScore", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("evaluarScore_response", Namespace="/bmsc/crm")]
        public evaluarScore_response EvaluarScore([System.Xml.Serialization.XmlElementAttribute(Namespace="/bmsc/crm")] evaluarScore_request evaluarScore_request) {
            object[] results = this.Invoke("EvaluarScore", new object[] {
                        evaluarScore_request});
            return ((evaluarScore_response)(results[0]));
        }
        
        /// <remarks/>
        public void EvaluarScoreAsync(evaluarScore_request evaluarScore_request) {
            this.EvaluarScoreAsync(evaluarScore_request, null);
        }
        
        /// <remarks/>
        public void EvaluarScoreAsync(evaluarScore_request evaluarScore_request, object userState) {
            if ((this.EvaluarScoreOperationCompleted == null)) {
                this.EvaluarScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEvaluarScoreOperationCompleted);
            }
            this.InvokeAsync("EvaluarScore", new object[] {
                        evaluarScore_request}, this.EvaluarScoreOperationCompleted, userState);
        }
        
        private void OnEvaluarScoreOperationCompleted(object arg) {
            if ((this.EvaluarScoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EvaluarScoreCompleted(this, new EvaluarScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="/bmsc/crm")]
    public partial class evaluarScore_request {
        
        private string pNroSolicitudField;
        
        private string pGUIClienteField;
        
        private string pCodigoLoginUsuarioField;
        
        private string pCodigoAgenciaField;
        
        private string pCodigoSucursalField;
        
        private System.DateTime pFechaEjecucionField;
        
        private string pUsuarioField;
        
        private string pContrasenaField;
        
        private string pDominioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string pNroSolicitud {
            get {
                return this.pNroSolicitudField;
            }
            set {
                this.pNroSolicitudField = value;
            }
        }
        
        /// <remarks/>
        public string pGUICliente {
            get {
                return this.pGUIClienteField;
            }
            set {
                this.pGUIClienteField = value;
            }
        }
        
        /// <remarks/>
        public string pCodigoLoginUsuario {
            get {
                return this.pCodigoLoginUsuarioField;
            }
            set {
                this.pCodigoLoginUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string pCodigoAgencia {
            get {
                return this.pCodigoAgenciaField;
            }
            set {
                this.pCodigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string pCodigoSucursal {
            get {
                return this.pCodigoSucursalField;
            }
            set {
                this.pCodigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime pFechaEjecucion {
            get {
                return this.pFechaEjecucionField;
            }
            set {
                this.pFechaEjecucionField = value;
            }
        }
        
        /// <remarks/>
        public string pUsuario {
            get {
                return this.pUsuarioField;
            }
            set {
                this.pUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string pContrasena {
            get {
                return this.pContrasenaField;
            }
            set {
                this.pContrasenaField = value;
            }
        }
        
        /// <remarks/>
        public string pDominio {
            get {
                return this.pDominioField;
            }
            set {
                this.pDominioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/bmsc/crm")]
    public partial class Result {
        
        private string campoField;
        
        private string valorField;
        
        /// <remarks/>
        public string Campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="/bmsc/crm")]
    public partial class evaluarScore_response {
        
        private string pMensajeField;
        
        private string pRespuestaField;
        
        private Result[] pResultadoField;
        
        /// <remarks/>
        public string pMensaje {
            get {
                return this.pMensajeField;
            }
            set {
                this.pMensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string pRespuesta {
            get {
                return this.pRespuestaField;
            }
            set {
                this.pRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pResultado")]
        public Result[] pResultado {
            get {
                return this.pResultadoField;
            }
            set {
                this.pResultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EvaluarScoreCompletedEventHandler(object sender, EvaluarScoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EvaluarScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EvaluarScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public evaluarScore_response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((evaluarScore_response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591