//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efika.Crm.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListaMarketing.Web.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo validado correctamente..
        /// </summary>
        internal static string ArchivoValidado {
            get {
                return ResourceManager.GetString("ArchivoValidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la fila de cabecera o el archivo está vacío..
        /// </summary>
        internal static string CabeceraNoEncontrada {
            get {
                return ResourceManager.GetString("CabeceraNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La importación del archivo se ha cancelado..
        /// </summary>
        internal static string CancelacionImportacion {
            get {
                return ResourceManager.GetString("CancelacionImportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró cabecera de columna.
        /// </summary>
        internal static string ColumnaCabeceraNoEncontrada {
            get {
                return ResourceManager.GetString("ColumnaCabeceraNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del error : \r\n {0}.
        /// </summary>
        internal static string DetalleError {
            get {
                return ResourceManager.GetString("DetalleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando datos del archivo..
        /// </summary>
        internal static string EnviandoWorkflow {
            get {
                return ResourceManager.GetString("EnviandoWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo no contiene datos..
        /// </summary>
        internal static string ErrorDatosArchivo {
            get {
                return ResourceManager.GetString("ErrorDatosArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo no tiene la estructura esperada..
        /// </summary>
        internal static string ErrorFormatoArchivo {
            get {
                return ResourceManager.GetString("ErrorFormatoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta oportunidad no se puede marcar como aceptada..
        /// </summary>
        internal static string ErrorValidacionOportunidad {
            get {
                return ResourceManager.GetString("ErrorValidacionOportunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando archivo {0} ....
        /// </summary>
        internal static string EscribirArchivo {
            get {
                return ResourceManager.GetString("EscribirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro almacenado. Iniciando proceso en segundo plano....
        /// </summary>
        internal static string GrabadoEnCrm {
            get {
                return ResourceManager.GetString("GrabadoEnCrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabando registro de Lista de Marketing....
        /// </summary>
        internal static string GrabandoEnCrm {
            get {
                return ResourceManager.GetString("GrabandoEnCrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrieron errores en el proceso :.
        /// </summary>
        internal static string MensajeError {
            get {
                return ResourceManager.GetString("MensajeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al cerrar la oportunidad. Intentelo de nuevo m&amp;aacute;s tarde..
        /// </summary>
        internal static string MensajeErrorOportunidad {
            get {
                return ResourceManager.GetString("MensajeErrorOportunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo está siendo procesado en segundo plano. Puede cerrar esta ventana..
        /// </summary>
        internal static string MensajeOk {
            get {
                return ResourceManager.GetString("MensajeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La oportunidad se cerró correctamente..
        /// </summary>
        internal static string MensajeOkOportunidad {
            get {
                return ResourceManager.GetString("MensajeOkOportunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validando archivo recibido....
        /// </summary>
        internal static string ValidarArchivo {
            get {
                return ResourceManager.GetString("ValidarArchivo", resourceCulture);
            }
        }
    }
}
