//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace Efika.Crm.WebService.BMSCTraerSaldos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TraerSaldos_pttBinding", Namespace="/bmsc/clientes/TraerSaldosService")]
    public partial class TraerSaldosService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TraerSaldosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TraerSaldosService() {
            this.Url = global::Efika.Crm.WebService.Properties.Settings.Default.Efika_Crm_WebService_BMSCTraerSaldos_TraerSaldosService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TraerSaldosCompletedEventHandler TraerSaldosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TraerSaldos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("traerSaldos_response", Namespace="/brms/clientes")]
        public traerSaldos_response TraerSaldos([System.Xml.Serialization.XmlElementAttribute(Namespace="/brms/clientes")] traerSaldos_request traerSaldos_request) {
            object[] results = this.Invoke("TraerSaldos", new object[] {
                        traerSaldos_request});
            return ((traerSaldos_response)(results[0]));
        }
        
        /// <remarks/>
        public void TraerSaldosAsync(traerSaldos_request traerSaldos_request) {
            this.TraerSaldosAsync(traerSaldos_request, null);
        }
        
        /// <remarks/>
        public void TraerSaldosAsync(traerSaldos_request traerSaldos_request, object userState) {
            if ((this.TraerSaldosOperationCompleted == null)) {
                this.TraerSaldosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerSaldosOperationCompleted);
            }
            this.InvokeAsync("TraerSaldos", new object[] {
                        traerSaldos_request}, this.TraerSaldosOperationCompleted, userState);
        }
        
        private void OnTraerSaldosOperationCompleted(object arg) {
            if ((this.TraerSaldosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerSaldosCompleted(this, new TraerSaldosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="/brms/clientes")]
    public partial class traerSaldos_request {
        
        private decimal pCodClienteField;
        
        private string pUsuarioField;
        
        private string pContrasenaField;
        
        private string pDominioField;
        
        /// <remarks/>
        public decimal pCodCliente {
            get {
                return this.pCodClienteField;
            }
            set {
                this.pCodClienteField = value;
            }
        }
        
        /// <remarks/>
        public string pUsuario {
            get {
                return this.pUsuarioField;
            }
            set {
                this.pUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string pContrasena {
            get {
                return this.pContrasenaField;
            }
            set {
                this.pContrasenaField = value;
            }
        }
        
        /// <remarks/>
        public string pDominio {
            get {
                return this.pDominioField;
            }
            set {
                this.pDominioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/brms/clientes")]
    public partial class saldosContables {
        
        private decimal saldoContableField;
        
        /// <remarks/>
        public decimal saldoContable {
            get {
                return this.saldoContableField;
            }
            set {
                this.saldoContableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/brms/clientes")]
    public partial class saldosDisponibles {
        
        private decimal saldoDisponibleField;
        
        /// <remarks/>
        public decimal saldoDisponible {
            get {
                return this.saldoDisponibleField;
            }
            set {
                this.saldoDisponibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/brms/clientes")]
    public partial class monedas {
        
        private string monedaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/brms/clientes")]
    public partial class tiposCuentas {
        
        private string tipoCuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tipoCuenta {
            get {
                return this.tipoCuentaField;
            }
            set {
                this.tipoCuentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="/brms/clientes")]
    public partial class cuentas {
        
        private string cuentaField;
        
        /// <remarks/>
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="/brms/clientes")]
    public partial class traerSaldos_response {
        
        private cuentas[] pCuentasField;
        
        private tiposCuentas[] pTiposCuentasField;
        
        private monedas[] pMonedasField;
        
        private saldosDisponibles[] pSaldosDisponiblesField;
        
        private saldosContables[] pSaldosContablesField;
        
        private string pRespuestaField;
        
        private string pMensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pCuentas")]
        public cuentas[] pCuentas {
            get {
                return this.pCuentasField;
            }
            set {
                this.pCuentasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pTiposCuentas")]
        public tiposCuentas[] pTiposCuentas {
            get {
                return this.pTiposCuentasField;
            }
            set {
                this.pTiposCuentasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pMonedas")]
        public monedas[] pMonedas {
            get {
                return this.pMonedasField;
            }
            set {
                this.pMonedasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pSaldosDisponibles")]
        public saldosDisponibles[] pSaldosDisponibles {
            get {
                return this.pSaldosDisponiblesField;
            }
            set {
                this.pSaldosDisponiblesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pSaldosContables")]
        public saldosContables[] pSaldosContables {
            get {
                return this.pSaldosContablesField;
            }
            set {
                this.pSaldosContablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string pRespuesta {
            get {
                return this.pRespuestaField;
            }
            set {
                this.pRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string pMensaje {
            get {
                return this.pMensajeField;
            }
            set {
                this.pMensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TraerSaldosCompletedEventHandler(object sender, TraerSaldosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerSaldosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerSaldosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public traerSaldos_response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((traerSaldos_response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591