//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.276
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.276.
// 
#pragma warning disable 1591

namespace Efika.Crm.CargaDatos.ServiciosCarga {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosCargaSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosCarga : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IngresarOptionSetValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublicarOptionSetValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosMonedaClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosCarga() {
            this.Url = global::Efika.Crm.CargaDatos.Properties.Settings.Default.Efika_Crm_CargaDatos_ServiciosCarga_ServiciosCarga;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IngresarOptionSetValueCompletedEventHandler IngresarOptionSetValueCompleted;
        
        /// <remarks/>
        public event PublicarOptionSetValueCompletedEventHandler PublicarOptionSetValueCompleted;
        
        /// <remarks/>
        public event DatosMonedaClienteCompletedEventHandler DatosMonedaClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IngresarOptionSetValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int IngresarOptionSetValue(string esquemaOptionSet, string valor) {
            object[] results = this.Invoke("IngresarOptionSetValue", new object[] {
                        esquemaOptionSet,
                        valor});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IngresarOptionSetValueAsync(string esquemaOptionSet, string valor) {
            this.IngresarOptionSetValueAsync(esquemaOptionSet, valor, null);
        }
        
        /// <remarks/>
        public void IngresarOptionSetValueAsync(string esquemaOptionSet, string valor, object userState) {
            if ((this.IngresarOptionSetValueOperationCompleted == null)) {
                this.IngresarOptionSetValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngresarOptionSetValueOperationCompleted);
            }
            this.InvokeAsync("IngresarOptionSetValue", new object[] {
                        esquemaOptionSet,
                        valor}, this.IngresarOptionSetValueOperationCompleted, userState);
        }
        
        private void OnIngresarOptionSetValueOperationCompleted(object arg) {
            if ((this.IngresarOptionSetValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngresarOptionSetValueCompleted(this, new IngresarOptionSetValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PublicarOptionSetValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PublicarOptionSetValue(string esquemaOptionSet) {
            this.Invoke("PublicarOptionSetValue", new object[] {
                        esquemaOptionSet});
        }
        
        /// <remarks/>
        public void PublicarOptionSetValueAsync(string esquemaOptionSet) {
            this.PublicarOptionSetValueAsync(esquemaOptionSet, null);
        }
        
        /// <remarks/>
        public void PublicarOptionSetValueAsync(string esquemaOptionSet, object userState) {
            if ((this.PublicarOptionSetValueOperationCompleted == null)) {
                this.PublicarOptionSetValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublicarOptionSetValueOperationCompleted);
            }
            this.InvokeAsync("PublicarOptionSetValue", new object[] {
                        esquemaOptionSet}, this.PublicarOptionSetValueOperationCompleted, userState);
        }
        
        private void OnPublicarOptionSetValueOperationCompleted(object arg) {
            if ((this.PublicarOptionSetValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublicarOptionSetValueCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DatosMonedaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal DatosMonedaCliente(System.Guid transactioncurrencyid) {
            object[] results = this.Invoke("DatosMonedaCliente", new object[] {
                        transactioncurrencyid});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void DatosMonedaClienteAsync(System.Guid transactioncurrencyid) {
            this.DatosMonedaClienteAsync(transactioncurrencyid, null);
        }
        
        /// <remarks/>
        public void DatosMonedaClienteAsync(System.Guid transactioncurrencyid, object userState) {
            if ((this.DatosMonedaClienteOperationCompleted == null)) {
                this.DatosMonedaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosMonedaClienteOperationCompleted);
            }
            this.InvokeAsync("DatosMonedaCliente", new object[] {
                        transactioncurrencyid}, this.DatosMonedaClienteOperationCompleted, userState);
        }
        
        private void OnDatosMonedaClienteOperationCompleted(object arg) {
            if ((this.DatosMonedaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosMonedaClienteCompleted(this, new DatosMonedaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IngresarOptionSetValueCompletedEventHandler(object sender, IngresarOptionSetValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngresarOptionSetValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngresarOptionSetValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PublicarOptionSetValueCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DatosMonedaClienteCompletedEventHandler(object sender, DatosMonedaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosMonedaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosMonedaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591